all: 	spectre1 spectre2 spectre3 spectre4 spectre5 spectre6 spectre7 spectre8 spectre9 spectre10 spectre11 spectre12 spectre13 spectre14 spectre15

spectre1: spectre.c spectre_helper.c v1.c
	gcc -D __SPECTRE__V1 spectre.c spectre_helper.c v1.c -O0 -o spectre1 
	objdump -D spectre1 > spectre1.dis

spectre2: spectre.c spectre_helper.c v2.c
	gcc -D __SPECTRE__V2 spectre.c spectre_helper.c v2.c -O0 -o spectre2 
	objdump -D spectre2 > spectre2.dis

spectre3: spectre.c spectre_helper.c v3.c
	gcc -D __SPECTRE__V3 spectre.c spectre_helper.c v3.c -O0 -o spectre3 
	objdump -D spectre3 > spectre3.dis

spectre4: spectre.c spectre_helper.c v4.c
	gcc -D __SPECTRE__V4 spectre.c spectre_helper.c v4.c -O0 -o spectre4
	objdump -D spectre4 > spectre4.dis

spectre5: spectre.c spectre_helper.c v5.c
	gcc -D __SPECTRE__V5 spectre.c spectre_helper.c v5.c -O0 -o spectre5
	objdump -D spectre5 > spectre5.dis

spectre6: spectre.c spectre_helper.c v6.c
	gcc -D __SPECTRE__V6 spectre.c spectre_helper.c v6.c -O0 -o spectre6
	objdump -D spectre6 > spectre6.dis

spectre7: spectre.c spectre_helper.c v7.c
	gcc -D __SPECTRE__V7 spectre.c spectre_helper.c v7.c -O0 -o spectre7
	objdump -D spectre7 > spectre7.dis

spectre8: spectre.c spectre_helper.c v8.c
	gcc -D __SPECTRE__V8 spectre.c spectre_helper.c v8.c -O0 -o spectre8
	objdump -D spectre8 > spectre8.dis

spectre9: spectre.c spectre_helper.c v9.c
	gcc -D __SPECTRE__V9 spectre.c spectre_helper.c v9.c -O0 -o spectre9
	objdump -D spectre9 > spectre9.dis

spectre10: spectre.c spectre_helper.c v10.c
	gcc -D __SPECTRE__V10 spectre.c spectre_helper.c v10.c -O0 -o spectre10
	objdump -D spectre10 > spectre10.dis

spectre11: spectre.c spectre_helper.c v11.c
	gcc -D __SPECTRE__V11 spectre.c spectre_helper.c v11.c -O0 -o spectre11
	objdump -D spectre11 > spectre11.dis

spectre12: spectre.c spectre_helper.c v12.c
	gcc -D __SPECTRE__V12 spectre.c spectre_helper.c v12.c -O0 -o spectre12
	objdump -D spectre12 > spectre12.dis

spectre13: spectre.c spectre_helper.c v13.c
	gcc -D __SPECTRE__V13 spectre.c spectre_helper.c v13.c -O0 -o spectre13
	objdump -D spectre13 > spectre13.dis

spectre14: spectre.c spectre_helper.c v14.c
	gcc -D __SPECTRE__V14 spectre.c spectre_helper.c v14.c -O0 -o spectre14
	objdump -D spectre14 > spectre14.dis

spectre15: spectre.c spectre_helper.c v15.c
	gcc -D __SPECTRE__V15 spectre.c spectre_helper.c v15.c -O0 -o spectre15
	objdump -D spectre15 > spectre15.dis

clean:
	rm -f spectre1
	rm -f spectre1.dis
	rm -f spectre2
	rm -f spectre2.dis
	rm -f spectre3
	rm -f spectre3.dis
	rm -f spectre4
	rm -f spectre4.dis
	rm -f spectre5
	rm -f spectre5.dis
	rm -f spectre6
	rm -f spectre6.dis
	rm -f spectre7
	rm -f spectre7.dis
	rm -f spectre8
	rm -f spectre8.dis
	rm -f spectre9
	rm -f spectre9.dis
	rm -f spectre10
	rm -f spectre10.dis
	rm -f spectre11
	rm -f spectre11.dis
	rm -f spectre12
	rm -f spectre12.dis
	rm -f spectre13
	rm -f spectre13.dis
	rm -f spectre14
	rm -f spectre14.dis
	rm -f spectre15
	rm -f spectre15.dis
